# Generated by Django 5.2.1 on 2025-05-30 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='newsletter_abo',
            field=models.BooleanField(default=True),
        ),
    ]
