# Generated by Django 5.2.1 on 2025-05-30 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_customer_newsletter_abo'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='email_address',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
