# Generated by Django 5.2.1 on 2025-05-30 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_bill_product_order_producttype_order_products'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producttype',
            options={'verbose_name': 'Producttype', 'verbose_name_plural': 'Producttypes'},
        ),
    ]
